language: go
sudo: false

go:
  - "1.9.x"
go_import_path: github.com/ihexxa/quickshare
script:
  - wget -O dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
  - chmod +x dep
  - ./dep ensure
  - yarn
  - yarn test
